@startuml FC-TRONTO_raspi

file main.py
file serialCom.py
file imageProc.py
file motorContl.py
database multiprocessing.Value {
  folder shmem [
    irAngle
    uSonicDis
  ]
}

main.py --> serialCom.py : 起動
main.py --> motorContl.py : 起動
motorContl.py ..> imageProc.py : include
main.py --> multiprocessing.Value : 作成・初期化
serialCom.py --> shmem : 書き込み
motorContl.py --> shmem : 読み込み

@enduml